theme: jekyll-theme-minimal
title: "aryoda´s wiki site around R programming"
description: You can find a list of all publication related to the R programming language (i. e. source code, packages, training slides)
